### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by Toflar** [contao/easy-coding-standard#11]
Just wanted to draw your attention to https://github.com/symplify/easy-coding-standard/releases/tag/9.4.67
Could speed up the CS fixing process quite a bit ;-)

**Comment by leofeyer** [comment]
Nice. 👍 We cannot currently update because of https://github.com/symplify/symplify/issues/3630, but as soon as this has been fixed, I am going to give it a shot.

**Comment by leofeyer** [comment]
Enabled in 33a1b89545da1b2cd293c2820b9b0d0d2ef4a29b.
