### ISSUE TITLE
TypeHintOrderFixer creates union types on PHP 7.4

### ISSUE THREAD

**Issue by bezin** [contao/easy-coding-standard#14]
The TypeHintOrderFixer always creates union types, causing incompatible changes for PHP 7.4, e.g. `?string` will always be "fixed" to `string|null`

See https://github.com/contao/easy-coding-standard/blob/main/src/Fixer/TypeHintOrderFixer.php#L180-L212

I am not familiar with the internals of ECS, so I don't know how to properly fix this.

**Comment by bezin** [comment]
I just saw that it is skipped by default in the monorepo for [5.x](https://github.com/contao/contao/blob/5.x/tools/ecs/config/default.php#L23) and [4.13](https://github.com/contao/contao/blob/4.13/tools/ecs/config/default.php#L23)

**Comment by leofeyer** [comment]
Correct. The fixer is PHP 8.1 only.
