### ISSUE TITLE
how to 'ignore a single line with a unused variable'

### ISSUE THREAD

**Issue by cmette** [contao/easy-coding-standard#16]
We want to suppress the error message 'unused variable' for a single line. We do not want to configure this globally. How can we achieve this?

**Comment by MDevster** [comment]
The following function from the documentation is to be used: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file

Unfortunately `// phpcs:disable`, `// phpcs:enable` or `// phpcs:ignore` is currently not supported.

**Comment by leofeyer** [comment]
Do `@codingStandardsIgnoreStart` and `@codingStandardsIgnoreEnd` work?

**Comment by MDevster** [comment]
No, unfortunately not.

**Comment by leofeyer** [comment]
Guess you are looking for this then: https://tomasvotruba.com/blog/2018/06/04/how-to-migrate-from-php-code-sniffer-to-easy-coding-standard#2-from-code-at-codingstandardsignorestartcode-to-codeskipcode-parameter
