### ISSUE TITLE
CS Fixer kills `/** @psalm-x */` annotations

### ISSUE THREAD

**Issue by m-vo** [contao/easy-coding-standard#2]
**How to reproduce**

Run the cs fixer on this code:
```
<?php
/** @psalm-suppress ImpureMethodCall */
$a = Foo::bar($b);
```

It will return:
```
<?php
/* @psalm-suppress ImpureMethodCall */
$a = Foo::bar($b);
```

This, however, will render the annotation ineffective.

**Comment by ausi** [comment]
I had the same problem in https://github.com/contao/imagine-svg/blob/539e87f89916fea673d7fba6c9393fadc54d9b43/tests/ImagineTest.php#L228-L237 and fixed it by moving the psalm annotation up to the doccomment (which is not optimal).

Did you check if it is possible to configure psalm to parse `/* */` comments too?

**Comment by leofeyer** [comment]
Is it really necessary to use these annotations? We have once agreed that we do not write code for certain IDEs or tools and try to configure them in their settings menu or configuration file instead.

**Comment by m-vo** [comment]
> We have once agreed that we do not write code for certain IDEs or tools

I still think this should be the case for IDE tools (as we do not want to force people to use a certain IDE). But for tools in our tool chain (installable via composer) we imo should reevaluate that. 

Otherwise a whole set of psalm features would not be usable to us. E.g. things that PHP lacks right now like the concept of class/variable immutability (or rather the ability to check those). In the special case of 'pureness' the need to suppress things is crucial when dealing with legacy code.

> Did you check if it is possible to configure psalm to parse /* */ comments too?

I didn't find anything yet (but only did a quick search).

**Comment by leofeyer** [comment]
* Bug report: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4446
* PR (currently unmerged): https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4649

I am not sure if the PR is still active though. We might have to set the `phpdoc_to_comment` option to `false` if not.

**Comment by leofeyer** [comment]
Maybe we should ask the Psalm developers why they do not support regular comments such as `/* @psalm-suppress */`? Because PhpStan does support `/* @phpstan-ignore-next-line */`.

**Comment by leofeyer** [comment]
Seems they will not do this: https://github.com/vimeo/psalm/issues/2344

**Comment by ausi** [comment]
How about adding a very specific custom fixer?

For all single line `/*…*/` comments: Make it a `/**` comment if it starts with an `@` otherwise make it a `/*` comment.

**Comment by leofeyer** [comment]
Added in 99a17fbb52291300fd73067bd59a3ae91a048d84.
